<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-ios</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>UnoPublishTest</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>uno.platform.publishtest</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.11</ApplicationDisplayVersion>
    <ApplicationVersion>12</ApplicationVersion>
    <!-- Package Publishe -->
    <ApplicationPublisher>Martin</ApplicationPublisher>
    <!-- Package Description -->
    <Description>UnoPublishTest powered by Uno Platform.</Description>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
        SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
    <PackageReference Include="SkiaSharp.NativeAssets.iOS" />
  </ItemGroup>
</Project>
