<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios;net9.0-browserwasm;net9.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>UnoPublishTest</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>uno.platform.publishtest</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.7</ApplicationDisplayVersion>
    <ApplicationVersion>8</ApplicationVersion>
    <!-- Package Publishe -->
    <ApplicationPublisher>Martin</ApplicationPublisher>
    <!-- Package Description -->
    <Description>UnoPublishTest powered by Uno Platform.</Description>

    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
        SkiaRenderer;
    </UnoFeatures>

      <MtouchExtraArgs>
          $(MtouchExtraArgs)
          --linker-flags="-Wl,-u,_sk_canvas_draw_text_blob -Wl,-u,_sk_canvas_set_matrix -Wl,-u,_sk_rrect_set_rect_radii -Wl,-u,_sk_textblob_builder_alloc_run_pos -Wl,-u,_sk_textblob_builder_make -Wl,-u,_sk_textblob_unref"
      </MtouchExtraArgs>
  </PropertyGroup>
</Project>
